### ISSUE TITLE
["SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large

### ISSUE THREAD

**Issue by retop** [verbb/formie#1289]
### Describe the bug

Creating a form with a lots of field (over 100) formie throws the following errror:

Unable to save form: {"general":["SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs\nThe SQL being executed was: ALTER TABLE `fmc_antragpflegegrad` ADD `field_ortGgfLand4_drhcwwqf` varchar(255)"]}.

I found this issue: https://github.com/verbb/formie/issues/1064 but the mentioned console command "prune-content-table-fields" results in the following error:

Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: verbb\formie\elements\Form::getFields()'
in /home/mecurio-craftcms/testing/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /home/mecurio-craftcms/testing/vendor/craftcms/cms/src/base/Element.php(2094): yii\base\Component->__call()
#1 /home/mecurio-craftcms/testing/vendor/verbb/formie/src/services/Forms.php(781): craft\base\Element->__call()
#2 /home/mecurio-craftcms/testing/vendor/verbb/formie/src/console/controllers/GcController.php(91): verbb\formie\services\Forms->pruneContentTableFields()
#3 [internal function]: verbb\formie\console\controllers\GcController->actionPruneContentTableFields()
#4 /home/mecurio-craftcms/testing/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /home/mecurio-craftcms/testing/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#6 /home/mecurio-craftcms/testing/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#7 /home/mecurio-craftcms/testing/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#8 /home/mecurio-craftcms/testing/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#9 /home/mecurio-craftcms/testing/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction()
#10 /home/mecurio-craftcms/testing/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#11 /home/mecurio-craftcms/testing/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest()
#12 /home/mecurio-craftcms/testing/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#13 /home/mecurio-craftcms/testing/craft(13): yii\base\Application->run()
#14 {main}

### Steps to reproduce

1. Create a long form with lots of fields 
2. error

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax and Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.3.8.2

### Plugin version

2.0.21

### Multi-site?

No

**Comment by engram-design** [comment]
There's nothing much we can do about this at the moment, sorry - It's down to the nature of MySQL. This will hopefully be addressed in future Craft versions (maybe Craft 5) with the concept of field instances, and maybe something tricky with splitting content tables.

However, we do have an experimental setting that changes many common fields to use `TEXT` as their MySQL column data type, instead of `VARCHAR(255)`. Using `TEXT` drastically decreases the number of bytes needed to store content. However, it's not without a slight performance hit.

if you're interested in the theory behind this:

> According to https://dev.mysql.com/doc/refman/8.0/en/column-count-limit.html#row-size-limits switching columns to use TEXT instead of VARCHAR(255) (which by default Craft fields all use) is an approach because instead of 255 bytes, it takes up 9 to 12 bytes

To enable this change in storage, set the `enableLargeFieldStorage` plugin setting to true in your [configuration](https://verbb.io/craft-plugins/formie/docs/get-started/configuration) and re-save your form.

The reason for the experimental nature of this setting is that we just need performance test the implication of this, and not everyone creates forms of that scale for it to be the default.

But regardless of this setting, at _some point_ you will reach a maximum number of fields. What that number is, is entirely up to the types of fields you use, but with this setting, it should be more like 300-400.

As for the command, that's purely for users who get this error with way under the limit of fields in their form. This was due to a bug in previous versions with synced fields getting duplicated, and not having them cleaned up when deleted. Hence, content tables have way more columns than fields, and this error is hit. But that command will cleanup those tables.

That error should be fixed for the next release, but I don't think that applies in your case.

**Comment by roland-d** [comment]
Hello,

I am going to jump on this as well as we have the same exact issue. I also found issue #1064 :)

Our customer has a form with 20 fields and the database shows 124 fields, so that has gone a bit rampant. Same as @retop when I run the `./craft formie/gc/prune-content-table-fields` I get the error `Error: Calling unknown method: verbb\formie\elements\Form::getFields()`.

We are running Formie 2.0.12 on PHP 8.1.8 and Craft 4.3.0.

Is the only solution for now to enable the `enableLargeFieldStorage` ? Can I manually figure out which table columns should be removed?

**Comment by engram-design** [comment]
`enableLargeFieldStorage` is indeed your best bet, which changes almost all fields to use non-varchar storage for field content.

So there might be two issues at play. One is that you've used synced fields and there are leftover columns in the content table. This is referred to in https://github.com/verbb/formie/issues/1064

The other issue is that the _row_ for a content table is too large for the database engine to handle. This means that there are also too many columns, but they be optimised to use a `TEXT` type instead, which allows for better memory storage (long story short).

So if you're getting this error, you might have a reasonably large form (20-50 fields), and you just need to optimise the storage of things.

**Comment by roland-d** [comment]
@engram-design Ok, so I created a file called `formie.php` in the folder `config` with the following content:
```php
return [
	'*' => [
		'enableLargeFieldStorage' => true,
	]
];
```
After that I saved the form again but I still get the same error message.

Looking a the table definition there does not seem to be anything changed either. Searching through the code I see no mention of the word `enableLargeFieldStorage` either. :confused: 

What can I try next?

This is the DDL of the table in question:
```sql
CREATE TABLE `x_fmc_eventform` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `elementId` int(11) NOT NULL,
  `siteId` int(11) NOT NULL,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) NOT NULL DEFAULT '0',
  `field_FirstName_jsgmoshr` varchar(255) DEFAULT NULL,
  `field_FirstName_iqmfrpgn` varchar(255) DEFAULT NULL,
  `field_FirstName_bcvimjza` varchar(255) DEFAULT NULL,
  `field_FirstName_wyqxjqzz` varchar(255) DEFAULT NULL,
  `field_FirstName_qnxpxocd` varchar(255) DEFAULT NULL,
  `field_LastName_igotstyi` varchar(255) DEFAULT NULL,
  `field_LastName_qkekjtze` varchar(255) DEFAULT NULL,
  `field_LastName_rvmatenb` varchar(255) DEFAULT NULL,
  `field_LastName_gssrjnqg` varchar(255) DEFAULT NULL,
  `field_LastName_tbcjryiw` varchar(255) DEFAULT NULL,
  `field_Company_npegkciu` varchar(255) DEFAULT NULL,
  `field_Company_dvrpqcul` varchar(255) DEFAULT NULL,
  `field_Company_aanjnbhy` varchar(255) DEFAULT NULL,
  `field_Company_eanfubyr` varchar(255) DEFAULT NULL,
  `field_Company_awnlqkhh` varchar(255) DEFAULT NULL,
  `field_JobTitle_rzbicpfh` varchar(255) DEFAULT NULL,
  `field_JobTitle_hwtmfmwd` varchar(255) DEFAULT NULL,
  `field_JobTitle_mcdmsqkf` varchar(255) DEFAULT NULL,
  `field_JobTitle_zqfgbbnv` varchar(255) DEFAULT NULL,
  `field_Email_lfmydpyt` varchar(255) DEFAULT NULL,
  `field_Email_qpwhuntg` varchar(255) DEFAULT NULL,
  `field_Email_vsnvuhjr` varchar(255) DEFAULT NULL,
  `field_Email_zmxhbhio` varchar(255) DEFAULT NULL,
  `field_Email_zvspxoko` varchar(255) DEFAULT NULL,
  `field_Phone_fdszaxdg` text DEFAULT NULL,
  `field_Phone_cmtymlll` text DEFAULT NULL,
  `field_Phone_kquexpjf` text DEFAULT NULL,
  `field_Phone_lagtxzsw` text DEFAULT NULL,
  `field_Phone_orzhwhfr` text DEFAULT NULL,
  `field_CountryCode_enqzprfw` varchar(255) DEFAULT NULL,
  `field_CountryCode_sbxdusls` varchar(255) DEFAULT NULL,
  `field_CountryCode_mvgzjcrj` varchar(255) DEFAULT NULL,
  `field_CountryCode_pngsuzxs` varchar(255) DEFAULT NULL,
  `field_CountryCode_uijukblc` varchar(255) DEFAULT NULL,
  `field_StateCode_ujkgxjgt` varchar(255) DEFAULT NULL,
  `field_StateCode_ghdmxuna` varchar(255) DEFAULT NULL,
  `field_StateCode_sfcsqbnt` varchar(255) DEFAULT NULL,
  `field_StateCode_zjqspgqh` varchar(255) DEFAULT NULL,
  `field_StateCode_sotsmcec` varchar(255) DEFAULT NULL,
  `field_PrivacyPolicy_wojtjjzw` tinyint(1) DEFAULT NULL,
  `field_PrivacyPolicy_vvvcfyol` tinyint(1) DEFAULT NULL,
  `field_PrivacyPolicy_iaretuun` tinyint(1) DEFAULT NULL,
  `field_PrivacyPolicy_mqhflbdp` tinyint(1) DEFAULT NULL,
  `field_PrivacyPolicy_kmvbmtqb` tinyint(1) DEFAULT NULL,
  `field_GDPRformconsent_noowjush` tinyint(1) DEFAULT NULL,
  `field_GDPRformconsent_maxeeqhs` tinyint(1) DEFAULT NULL,
  `field_GDPRformconsent_vffmobni` tinyint(1) DEFAULT NULL,
  `field_GDPRformconsent_hwflklli` tinyint(1) DEFAULT NULL,
  `field_GDPRformconsent_uwdhjtwh` tinyint(1) DEFAULT NULL,
  `field_LeadSource_xiehldxc` varchar(255) DEFAULT NULL,
  `field_LeadSource_xjalfrha` varchar(255) DEFAULT NULL,
  `field_LeadSource_flxkunyf` varchar(255) DEFAULT NULL,
  `field_LeadSource_btpxjdfs` varchar(255) DEFAULT NULL,
  `field_LeadSource_yuqzycyf` varchar(255) DEFAULT NULL,
  `field_Campaign_Medium__c_ykrxxozu` varchar(255) DEFAULT NULL,
  `field_Campaign_Medium__c_rzzndqvy` varchar(255) DEFAULT NULL,
  `field_Campaign_Medium__c_qntpupmn` varchar(255) DEFAULT NULL,
  `field_Campaign_Medium__c_exkkuovp` varchar(255) DEFAULT NULL,
  `field_Campaign_Medium__c_gtvzufql` varchar(255) DEFAULT NULL,
  `field_Campaign_Tags__c_edsifqdw` varchar(255) DEFAULT NULL,
  `field_Campaign_Tags__c_cutsqkzk` varchar(255) DEFAULT NULL,
  `field_Campaign_Tags__c_vazzguec` varchar(255) DEFAULT NULL,
  `field_Campaign_Tags__c_bmqnoqwg` varchar(255) DEFAULT NULL,
  `field_Campaign_Tags__c_suxoiorz` varchar(255) DEFAULT NULL,
  `field_marketo_tndqwxdp` varchar(255) DEFAULT NULL,
  `field_marketo_nmutynkd` varchar(255) DEFAULT NULL,
  `field_pageURL_phwargjn` mediumtext DEFAULT NULL,
  `field_pageURL_junhjurz` mediumtext DEFAULT NULL,
  `field_DigitalServiceParing_zqpcsxsj` varchar(255) DEFAULT NULL,
  `field_HowCanWeHelp_vjamzoni` varchar(255) DEFAULT NULL,
  `field_FirstName` varchar(255) DEFAULT NULL,
  `field_LastName` varchar(255) DEFAULT NULL,
  `field_Company` varchar(255) DEFAULT NULL,
  `field_JobTitle` varchar(255) DEFAULT NULL,
  `field_JobSeniority__c_msmifzdz` varchar(255) DEFAULT NULL,
  `field_JobSeniority__c_ksiwmcne` varchar(255) DEFAULT NULL,
  `field_JobSeniority__c` varchar(255) DEFAULT NULL,
  `field_JobSeniority__c_ldlqkzij` varchar(255) DEFAULT NULL,
  `field_JobSeniority__c_inmrssmy` varchar(255) DEFAULT NULL,
  `field_Email` varchar(255) DEFAULT NULL,
  `field_Phone` text DEFAULT NULL,
  `field_CountryCode` varchar(255) DEFAULT NULL,
  `field_StateCode` varchar(255) DEFAULT NULL,
  `field_PrivacyPolicy` tinyint(1) DEFAULT NULL,
  `field_GDPRformconsent` tinyint(1) DEFAULT NULL,
  `field_LeadSource` varchar(255) DEFAULT NULL,
  `field_Campaign_Medium__c` varchar(255) DEFAULT NULL,
  `field_Campaign_Tags__c` varchar(255) DEFAULT NULL,
  `field_marketo` varchar(255) DEFAULT NULL,
  `field_pageURL` mediumtext DEFAULT NULL,
  `field_Industry_pyhbxkgx` varchar(255) DEFAULT NULL,
  `field_Industry` varchar(255) DEFAULT NULL,
  `field_Industry_fwzctafp` varchar(255) DEFAULT NULL,
  `field_PersonSource_qfysmijf` text DEFAULT NULL,
  `field_PersonSource_bdardgnm` text DEFAULT NULL,
  `field_PersonSource_ymrmsqdu` text DEFAULT NULL,
  `field_PersonSource_lbrplbwj` text DEFAULT NULL,
  `field_PersonSource_btxvucnx` text DEFAULT NULL,
  `field_PersonSource_thhgrdhd` text DEFAULT NULL,
  `field_PersonSource_kmbpzyqi` text DEFAULT NULL,
  `field_PersonSource_bpgtikmp` text DEFAULT NULL,
  `field_PersonSource_mopdnrjl` text DEFAULT NULL,
  `field_PersonSource_xwrfmglz` text DEFAULT NULL,
  `field_PersonSource_glfamjbn` text DEFAULT NULL,
  `field_PersonSource_ujocqdpj` text DEFAULT NULL,
  `field_PersonSource_kadlzcnh` text DEFAULT NULL,
  `field_PersonSource_qccjsvyr` text DEFAULT NULL,
  `field_FirstName_pxvhfiik` varchar(255) DEFAULT NULL,
  `field_LastName_kfsxwnzk` varchar(255) DEFAULT NULL,
  `field_Company_nosuxcih` varchar(255) DEFAULT NULL,
  `field_Industry_xifgsbsn` varchar(255) DEFAULT NULL,
  `field_JobTitle_bmslxecw` varchar(255) DEFAULT NULL,
  `field_JobSeniority__c_hvogfhit` varchar(255) DEFAULT NULL,
  `field_Email_rdsjsjhx` varchar(255) DEFAULT NULL,
  `field_Email_ldxxjfzs` varchar(255) DEFAULT NULL,
  `field_Phone_chgmmjxq` text DEFAULT NULL,
  `field_CountryCode_crvudjbl` varchar(255) DEFAULT NULL,
  `field_StateCode_eqrhilkm` varchar(255) DEFAULT NULL,
  `field_PrivacyPolicy_tpnhmukb` tinyint(1) DEFAULT NULL,
  `field_PrivacyPolicy_kgeqlysy` tinyint(1) DEFAULT NULL,
  `field_GDPRformconsent_bojqlmou` tinyint(1) DEFAULT NULL,
  `field_GDPRformconsent_ixstpagq` tinyint(1) DEFAULT NULL,
  `field_LeadSource_tmilaxdb` varchar(255) DEFAULT NULL,
  `field_LeadSource_dguolqcs` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `x_idx_frkkizzisfxmnyvurnzzmsgtuhacerthotop` (`elementId`,`siteId`),
  KEY `x_fk_fvbcnwetfavoljcervoztppoktntfczqlzam` (`siteId`),
  CONSTRAINT `x_fk_fvbcnwetfavoljcervoztppoktntfczqlzam` FOREIGN KEY (`siteId`) REFERENCES `x_sites` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `x_fk_pdwglpsfeklvgupqizcrpnsxzoolgvvhnegz` FOREIGN KEY (`elementId`) REFERENCES `x_elements` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=158 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
```

**Comment by engram-design** [comment]
`enableLargeFieldStorage` was only added in [2.0.21](https://github.com/verbb/formie/blob/craft-4/CHANGELOG.md#2021---2023-01-30)

**Comment by roland-d** [comment]
Thank you, I did not register that 2.0.12 is not 2.0.21 :) I have updated the site and have seen the columns changed to `text`. Will post if anymore issues arise in regards to this. Thank you.

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
