### ISSUE TITLE
Notification doesn't output grouped field tokens

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#129]
**Description**
A similar problem as issue #128 

I have a form where I use grouped fields:
![Screen Shot 2020-09-22 at 13 55 24 PM](https://user-images.githubusercontent.com/16959207/93879525-20b5a000-fcdc-11ea-993a-1744214c127a.png)

When I add a notification I have two issues:
1. **The fields in the second group aren't picked up by Formie as tokens** (you notice the absence of the message field):
![Screen Shot 2020-09-22 at 14 02 34 PM](https://user-images.githubusercontent.com/16959207/93879686-72f6c100-fcdc-11ea-9b02-2e44d3ddcf0c.png)

2. **None of the grouped fields are shown in the notification** even though it is selected in the e-mail content window:

What I want:
![Screen Shot 2020-09-22 at 13 55 56 PM](https://user-images.githubusercontent.com/16959207/93879752-97529d80-fcdc-11ea-9654-524b3c2ea3fc.png)

What it shows:
![Screen Shot 2020-09-22 at 13 56 15 PM](https://user-images.githubusercontent.com/16959207/93879761-9c175180-fcdc-11ea-9bcf-82b512204eb5.png)

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.16
- Craft version: 3.5.11.1
- Multi-site: No

**Comment by engram-design** [comment]
Just fixed for the next release.

To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.16",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.2.17](https://github.com/verbb/formie/releases/tag/1.2.17)

**Comment by TomDeSmet** [comment]
The real notification works but the preview is rather scrambled: 

![Screen Shot 2020-09-23 at 17 14 28 PM](https://user-images.githubusercontent.com/16959207/94032923-bf1b3180-fdc0-11ea-9fbe-e2bb609b7969.png)

**Comment by engram-design** [comment]
Can you provide a screenshot of your email content? It looks like you're using a variable that references the group field, which returns an element query - instead of the individual field inside the group. You may also have to re-add your variable fields which are inside a group.

**Comment by TomDeSmet** [comment]
I had chosen only the single field variables and not the group variable, but I didn't re-add them. After adding them again, they show up correctly BUT **the fields from the second group are still missing**...

![Screen Shot 2020-09-24 at 09 09 00 AM](https://user-images.githubusercontent.com/16959207/94112462-c9334380-fe45-11ea-8c53-76a925fcc463.png)
