### ISSUE TITLE
Console error originating from JS captcha cache bust code

### ISSUE THREAD

**Issue by jwrudzin** [verbb/formie#1568]
### Describe the bug

I have a form that is being displayed multiple times on a page, and the form is being cached. Since the form is cached, I am using the [provided code to refresh the tokens](https://verbb.io/craft-plugins/formie/docs/template-guides/cached-forms).

The line that refreshes the JavaScript captcha (`$form.querySelector('input[name="' + jsCaptcha.sessionKey + '"]').value = jsCaptcha.value;`) is throwing a console error: `Uncaught (in promise) TypeError: Cannot set properties of null (setting 'value')`.

The page in question is a test page, and it has 6 instances of the same form on it. The behavior seemed very inconsistent prior to the most recent Formie update, but after the most recent Formie update it seems to have become more consistent and is now being thrown for every instance of the form except one on some page loads, and on other page loads the error is thrown for every instance of the form.

I have a single instance of a different form on the page, and that form does not throw the error, so this does seem related to having multiple instances of a form on the same page.

Here is my cache busting JavaScript:

```
{# Ensure we load polyfills for older browsers that don't support `fetch()` #}
{% js "https://cdn.polyfill.io/v2/polyfill.js?features=fetch,Promise" %}
{% js %}
	// Formie Cache Busting
	document.addEventListener('DOMContentLoaded', (event) => {
		let $form = document.querySelector('#{{ formieForm.formId }}');
		let $csrfInput = $form.querySelector('input[name="CRAFT_CSRF_TOKEN"]');

		fetch('/actions/formie/forms/refresh-tokens?form={{ formieForm.handle }}')
			.then(result => { return result.json(); })
			.then(result => {
				$csrfInput.outerHTML = result.csrf.input;
				
				console.log('form cache bust');
				console.log($form);
				console.log(result);
				

				// Find the JavaScript captcha hidden input, so we can update it
				if (result.captchas && result.captchas.javascript) {
					// JavaScript captcha
					let jsCaptcha = result.captchas.javascript;
					console.log('input[name="' + jsCaptcha.sessionKey + '"]');
					$form.querySelector('input[name="' + jsCaptcha.sessionKey + '"]').value = jsCaptcha.value;
				}

				// Find the Duplicate captcha hidden input, so we can update it
				if (result.captchas && result.captchas.duplicate) {
					// Duplicate captcha
					let duplicateCaptcha = result.captchas.duplicate;

					$form.querySelector('input[name="' + duplicateCaptcha.sessionKey + '"]').value = duplicateCaptcha.value;
				}

				if ($form.form && $form.form.formTheme) {
						$form.form.formTheme.updateFormHash();
				}
			});
	});
{% endjs %}
```

I've done some digging, and what I'm seeing is that `result.captchas.javascript.formID` does not match the form ID in the script itself (`formieForm.formId`) where the error originates (not sure if this matters). A form with an ID matching `result.captchas.javascript.formID` does not exist on the page at all. However, the form with ID `formieForm.formId` seen in the script does exist.

Notably, an input with a name attribute matching `result.captchas.javascript.sessionKey` does exist, but not necessarily in the instance of the form associated with the script that is throwing the error. However, I'm seeing the same error thrown from the script associated with the form that _does_ have the input matching that name attribute, which is very puzzling.

Is having more than one instance of a form on a page supported? Perhaps I need to update my cache busting code to accommodate for multiple instances of a form on a page (is there a way to pass a form ID to the refresh-tokens endpoint, rather than the form handle)?

Please let me know what questions you have or what I can do to dig into this further. I'm also happy to set up a page where you can see the issue yourself if that would be useful.

I also want to note that this seems related to [issue #355](https://github.com/verbb/formie/issues/355).

I appreciate your help!

### Steps to reproduce

1. Add multiple instances of a cached Formie form to a single page.
2. Enable JS captcha, and add cache busting code.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.5

### Plugin version

2.0.36

### Multi-site?

No

**Comment by engram-design** [comment]
The idea is that you'll include the JS snippet for every time you call `craft.formie.renderForm()`. For this reason, it might be a good idea to make that a Twig include and include the JS alongside that.

The example JS does use an `id` selector to target a form, which will cause issues when rendering the same form multiple times on the page. This is the `formieForm.formId` Twig call, which is unique to each form, but will be the same if you're fetching the form once and rendering it multiple times.

You can completely modify the `formId` though if you like:

```twig
{% set form = craft.formie.forms({ handle: 'contactForm' }).one() %}

{# Render form once #}
{% do form.setFormId('form_' ~ random()) %}
{{ form.formId }}

{% include 'forms/form' with { form: form } %}

{# Render form again #}
{% do form.setFormId('form_' ~ random()) %}
{{ form.formId }}

{% include 'forms/form' with { form: form } %}
```

The `forms/form` include would be:
```twig
{{ craft.formie.renderForm(form) }}

{% js %}
...the JS snippet to refresh
```

This would produce
```twig
form_2001470081
<form>...

form_1436197987
<form>...
```

The reason for this is that each form needs their own CSRF token that's unique. Once a CSRF token has been "used" (i.e. a form has been submitted) it can no longer be used.

Adding a unique formID is something we've been looking at adding automatically in `craft.formie.renderForm()` but that'll mess up people doing things like this where they want to have a specific ID for the form to keep track of.

**Comment by jwrudzin** [comment]
@engram-design thanks for the info.

In our case, we are fetching the form each time before it's rendered, we're not fetching the form once and rendering it multiple times. We're fetching the form from a Forms (Formie) field, then rendering it. In the case in question, the same form has been selected for several different Forms (Formie) fields. In this case, would you still recommend explicitly setting the form ID as you outlined above?

To be clear, we're fetching the form from a Forms (Formie) field, setting formieForm to the form, outputting the JS from my initial post for each instance of the form, then calling renderForm (and passing formieForm to the renderForm method).

**Comment by engram-design** [comment]
Ah I see. But yep, it’s the same thing as you’re still using the same form multiple times.

**Comment by jwrudzin** [comment]
@engram-design I added the line `{% do form.setFormId('form_' ~ random()) %}` to explicitly set the form ID to something different each time, but unfortunately I'm still seeing the same console errors.

I noticed that only the first instance of the form has a hidden input with name beginning with `__JSCHK_` - for this instance of the form, the `__JSCHK_` input matches the selector that is being used in the JS (although it still sometimes throws the error, more info below). All subsequent instances of the form do not have any such hidden input. 

I'm also noticing some inconsistency - on a page with a lot more content to load, the console error is triggered for _every_ instance of the form, even the instance that has the input matching the selector (the first instance of the form). On this page, the error is also triggered for a form that only appears once on the page (and has a matching `__JSCHK_` input that theoretically should be found by the JS). On a page with much less content, the error does not trigger for the first instance of the form (the instance that has the input matching the selector) or the form that only appears one time, but triggers for all subsequent forms (which makes sense, because they do not have a `__JSCHK_` input).

Thanks again for your help here, let me know if there's anything I can provide to help further troubleshoot.

**Comment by engram-design** [comment]
So good call, there's an issue here with the JS binding. It was correctly checking against the scripts being output for the form, but it wasn't respecting the unique `formId` you were setting. That should be fixed.

You may have noticed a `Formie scripts already loaded for form #xxxxxxx` JS warning (not error) pointing to the cause of this issue.

In addition, we now also assign a unique `formId` each time you call `craft.formie.renderForm()`. This means you can do away with the `setFormId()` as I mentioned.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.37"`.

**Comment by jwrudzin** [comment]
@engram-design with the updated version, I can confirm that the `Formie scripts already loaded for form #xxxxxxx` warning did go away.

However, I'm running into a different issue now - the `let $csrfInput = $form.querySelector('input[name="CRAFT_CSRF_TOKEN"]');` line is throwing the error `Uncaught TypeError: Cannot read properties of null (reading 'querySelector')`. It seems that `form.formId` is now outputting a formId that does not match the ID of the form that is being output by `renderForm`.

I tried calling `setFormId()`, but it didn't change the behavior. With that in place, `form.formId` returned the ID I set, but `renderForm` still output the form with a different ID.

Thanks again for all the help! Let me know if there's any other information I can provide or testing you'd like me to do.

**Comment by engram-design** [comment]
@jwrudzin Right, so that line of JS:

```js
let $form = document.querySelector('#{{ form.formId }}');
```

Is returning `null`. Could you maybe run a `console.log('#{{ form.formId }}')` line after the above to confirm what the ID is being used, and if that matches what's rendered? Just ensure that your `craft.formie.renderForm()` and your cache-busting script are rendered for **each** form output (don't just output the JS once for the page), and alongside each other.

Also goes without saying to clear the Blitz cache.

If that's still not working, can you provide your full Twig + JS code you're using and what the rendered result is? Mainly I just want to know that the IDs are for each form's HTML.

**Comment by jwrudzin** [comment]
@engram-design So you have all the relevant info - I'm running Formie `dev-craft-4 as 2.0.37`, outputting the cache-busting script for each form (not just once) just before `renderForm` is called. We're not using Blitz on this site.

With that configuration, I'm still seeing this issue. I'm seeing the `Cannot read properties of null` error for every form instance, including the form that is only present one time on the page.

Running `console.log('#{{ form.formId }}')` immediately after the `let $form = document.querySelector('#{{ formieForm.formId }}');` line returns an ID that does not match any form ID being rendered.

Twig:
```
{# block.molCallToActionForm_form is a Formie form field #}
{% set formieForm = block.molCallToActionForm_form.one() ?? null %}

{# Ensure we load polyfills for older browsers that don't support `fetch()` #}
{% js "https://cdn.polyfill.io/v2/polyfill.js?features=fetch,Promise" %}
{% js %}
	// Formie Cache Busting
	document.addEventListener('DOMContentLoaded', (event) => {
		let $form = document.querySelector('#{{ formieForm.formId }}');
		console.log('#{{ formieForm.formId }}');
		let $csrfInput = $form.querySelector('input[name="CRAFT_CSRF_TOKEN"]');

		fetch('/actions/formie/forms/refresh-tokens?form={{ formieForm.handle }}')
			.then(result => { return result.json(); })
			.then(result => {
				$csrfInput.outerHTML = result.csrf.input;
				
				// Find the JavaScript captcha hidden input, so we can update it
				if (result.captchas && result.captchas.javascript) {
					// JavaScript captcha
					let jsCaptcha = result.captchas.javascript;

					$form.querySelector('input[name="' + jsCaptcha.sessionKey + '"]').value = jsCaptcha.value;
				}

				// Find the Duplicate captcha hidden input, so we can update it
				if (result.captchas && result.captchas.duplicate) {
					// Duplicate captcha
					let duplicateCaptcha = result.captchas.duplicate;

					$form.querySelector('input[name="' + duplicateCaptcha.sessionKey + '"]').value = duplicateCaptcha.value;
				}

				if ($form.form && $form.form.formTheme) {
						$form.form.formTheme.updateFormHash();
				}
			});
	});
{% endjs %}

{% set formieFormMarkup = craft.formie.renderForm(formieForm, {
	themeConfig: {
		form: {
			attributes: {
				class: baseClass ~ "__form",
			},
		},
	},
}) ?? false %}

{{ formieFormMarkup }}
```

The rendered form IDs are:
```
fui-demonstration-kuiwpe
fui-unitApplication-konhdu
fui-demonstration-nepgoy
fui-demonstration-hmcnta
fui-demonstration-qmxcjn
```

And the console output from the `console.log('#{{ formieForm.formId }}');` line:
```
#fui-demonstration-zgvcoa
#fui-unitApplication-kcjzxx
#fui-demonstration-kitbmv
#fui-demonstration-carosq
#fui-demonstration-viqaka
```

As always, let me know if there's anything else I can provide to help troubleshoot! Thanks!

**Comment by engram-design** [comment]
Ah, so adding the script _before_ the `renderForm()` will make a difference now, because `renderForm()` resets the `formId` for the form. So if you're doing it before this call, it's going to use the incorrect `formId` which is discarded as soon as you render the form.

**Comment by jwrudzin** [comment]
@engram-design Ah got it. Moved things around and it's working now, no console errors. Really appreciate all your help with this!

Any idea when this will make it into an official release? You can go ahead and close this issue, thanks again!

**Comment by engram-design** [comment]
Should be in the next day or so!

**Comment by engram-design** [comment]
Fixed in [2.0.38](https://github.com/verbb/formie/releases/tag/2.0.38)

**Comment by jwrudzin** [comment]
@engram-design I thought this issue was fixed, but I'm now seeing it again intermittently.

I'm stumped and am not sure what's going on, when I console log (just prior to the line throwing the error):

```
console.log($form);
console.log('input[name="' + jsCaptcha.sessionKey + '"]');
console.log($form.querySelector('input[name="' + jsCaptcha.sessionKey + '"]'));
```

I can see the input from the second console.log in the $form being logged to the console (in the first console.log), but the third statement logs `null` and then I get the same `Uncaught (in promise) TypeError: Cannot set properties of null (setting 'value')` I was seeing previously. 

The behavior is intermittent, sometimes there are no errors but on the majority of page loads I see the error on 1 or 2 of the 3 forms on the page in question. Could this be a timing issue? The one thing that's consistent is that when I see the error on any of the forms, the first form for which the JS runs always throws the error.

**Comment by engram-design** [comment]
So the `__JSCHK_*` name attribute will be the same on every form you render if the page is cached. Can you confirm what these names are for all the forms on your page when loaded?

And just to refresh my memory. How many forms are you rendering on a page, and are they unique or the same? Just want to try and replicate your setup as best I can.

**Comment by jwrudzin** [comment]
@engram-design The page where I'm seeing the error has 3 forms, 2 are the same and the 3rd is unique.

Form IDs and JSCHK names are:
```
fui-submitInterest-ukfiuw
__JSCHK_143831002

fui-unitApplication-wozway
__JSCHK_3734337

fui-submitInterest-zmamym
__JSCHK_143831002
```

So you're correct, the 2 non-unique forms have the same `__JSCHK_*` name attribute. It's worth noting that occasionally the error occurs for the unique form as well.

The strange thing is, we have a boilerplate/test site that has a page with 7 forms (6 are the same and the 7th is unique), and that page is not throwing any errors at all (which is why I initially reported that this error was fixed). The boilerplate site is running the exact same form code (and Formie version) as the site where I'm seeing the error, and I can see in the rendered HTML that the situation is the same as above - all 6 of the non-unique forms have unique IDs but all have the same `__JSCHK_*` name attribute.

The other thing is, on the site where the errors are occurring, the errors only occur on my local site. I also have the site on a staging server, and I'm not seeing any errors there. So this probably isn't a huge deal, but I want to make sure this is fully sorted out so am trying to figure out what could be going on so I can be sure it won't pop up on a production site.

One other note is that clearing the cache makes the error go away for one page load, but then on subsequent refreshes the error comes back. Also, as I mentioned before, the error does not occur on every subsequent page load, it's intermittent.

Thanks again for all your help on this!

**Comment by jwrudzin** [comment]
@engram-design Update to my previous comment:

I did some additional testing, and I did eventually see the error appear on the staging server (both on the actual site and the test site). It seems like it's much more rare as I had to refresh the page many times before I saw it, but I did see the error occur.

So at this point, I've seen the error on both the test site as well as the actual site on the staging server, and I'm seeing the error very often on the actual site on my local server. The error has never occurred on the test site on my local server, and I've tested thoroughly.

When it does occur, it's completely intermittent and random. Sometimes occurring multiple times and sometimes not at all.

What I still don't understand is, the line that returns null is looking for an element that does exist. Is that JSCHK input element being added to the form by JavaScript or something? I just don't understand why null is being returned there in the first place when I can see the input in the form.

If it would be helpful, I can give you access to the staging site so you can see the page and error yourself.

**Comment by engram-design** [comment]
The `JSCHK` input is indeed [created dynamically](https://github.com/verbb/formie/blob/ba4a6b1e481fb1c0fcf3ce69fcb93f77ac3fa930/src/web/assets/frontend/src/js/captchas/javascript.js#L24-L29) so it's possible there's a race condition going on - that's a good point. I wouldn't have thought that be entirely possible though, as the captcha's JS would fire **well** before the additional XHR request to fetch new tokens. Not to mention the delay in the response would be on our side, giving the element time to be created.

Are you maybe lazy-loading the form at all?

I'll look into alternatives, but that's **very** strange behaviour in my eyes.

**Comment by engram-design** [comment]
For a sanity check, the waterfall of loading should look something like this:

![image](https://github.com/verbb/formie/assets/1221575/6ed6b846-8c4c-46f0-8259-0ae343fc7556)

Where `javascript.js` is loading _before_`refresh-tokens`, and I'd hazard a guess that's not the case on your local site, whatever the reason. I'll look at adding a callback, or another means to set the captcha value in that case.

**Comment by engram-design** [comment]
I've gone ahead and created a new JS helper that should alleviate this issue, and simplify cache-handling for everyone.

To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.38"`.

Your new JS code can be cut way down to the following:

```js
document.addEventListener('onFormieInit', (event) => {
    // Fetch the Form Factory once it's been loaded
    let Formie = event.detail.formie;

    // Refresh the necessary bits that are statically cached (CSRF inputs, captchas, etc)
    Formie.refreshForCache('{{ form.formId }}');
});
```

All that's required is the `form` variable in Twig to be present (a Form element), and Formie will take care of the rest.

**Comment by jwrudzin** [comment]
@engram-design With the new update in place, I'm now getting an error from formie.js - `formie.js?v=1697719329:1 <formId>: Unable to locate captcha input for "javascript".` Unfortunately seems like the same problem as before.

I can see in the network waterfall that `javascript.js` comes before the calls to `refresh-tokens`, however it seems there is some overlap - if I sort the waterfall by end time instead of start time, I'm sometimes seeing `refresh-tokens` end before `javascript.js` and this is consistent with when I'm seeing the console error. In cases where there is no console error, all the calls to `refresh-tokens` end after `javascript.js` ends. In every case with a console error, the `refresh-tokens` call associated with the form from the error message ends before `javascript.js`.

Would it be possible to update the calls to `refresh-tokens` so they don't fire until after `javascript.js` has finished loading? If the code can guarantee that `javascript.js` is finished loading before `refresh-tokens` fires, it seems like that would fix the issue.

I appreciate the simplified JavaScript, and thanks again for continuing to work on this!

**Comment by engram-design** [comment]
Thanks for the investigation, it seems like that can narrow it down.

I’ll see what I can do about delaying the call, but it’s a bit trickier than that, as we need to check for all captchas are “ready” (if any are even enabled for the form) before making this call. Currently it’s only duplicate and JS captchas, but there’s other custom ones out there to cater for.

But I’ve got an idea of how to handle this.

**Comment by engram-design** [comment]
Alright, I believe this should be fixed for the next release, along with a few more improvements to captchas. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.38"`.

**Comment by engram-design** [comment]
Fixed in [2.0.39](https://github.com/verbb/formie/releases/tag/2.0.39)

**Comment by jwrudzin** [comment]
@engram-design This is working well, I'm not seeing any console errors anymore.

One thing - I'm now getting a "Reload site? Changes you made may not be saved." warning when I refresh the page every time, even if I don't type anything into any form. I confirmed that this wasn't happening before the 2.0.39 update.

**Comment by engram-design** [comment]
Possibly due to the revamped Duplicate captcha, if you're using that? If so, fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.39"`.

**Comment by jwrudzin** [comment]
@engram-design I see there's a new issue open now for the duplicate captcha, so you can go ahead and close this one and I'll follow the other issue. Thanks for all your help on this!
