### ISSUE TITLE
Admin Forms & Submission page not loading

### ISSUE THREAD

**Issue by karthikkstar** [verbb/formie#1654]
### Describe the bug

The following pages are not working after upgrading Craft 3.9.5 to Craft 4.5.11.1
admin/formie/forms?site=uk
admin/formie/submissions?site=uk

I noticed a console error.

> Uncaught SyntaxError: Invalid or unexpected token (at submissions?site=uk:1050:32)

`Craft.elementIndex = Craft.createElementIndex('verbb\\formie\\elements\\Form', $('#page-container'), {
        elementTypeName: 'Form',
        elementTypePluralName: '
Elements',
        context: 'index',
        storageKey: 'elementindex.verbb\\formie\\elements\\Form',
        criteria: Craft.defaultIndexCriteria,
        toolbarSelector: '#toolbar',
        defaultSource: null,
        defaultSourcePath: null,
        canHaveDrafts: false,
    });`
    
Whitespace added before the `elementTypePluralName: ' Elements'. `

![Screenshot from 2023-12-08 17-00-41](https://github.com/verbb/formie/assets/85233749/4d265ee2-a75f-4698-ba20-1fe15f64244e)

**NOTE**   Sent notifications and settings page is working fine.
   
Any ideas about this issue and its related Craft version?

### Steps to reproduce

After upgrading from  Craft 3.9.5 to Craft 4.5.11.1

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes 
- Custom Form Templates: Yes

### Craft CMS version

Craft Pro 4.5.11.1

### Plugin version

8.1.26

### Multi-site?

yes

### Additional context

Amazon S3	2.0.3
AsyncQueue	3.1.0
Cloner	2.0.4
Control Panel Body Classes	2.3.0
Default Dashboard	2.0.1
Device Detect	2.0.1
Feed Me	5.2.0
Fetch	2.0.0-beta.1
Formie	2.0.42
GeoMate	2.1.1
Maps	4.0.4
Myproperties	1.8.7
Password Policy	4.1.0
Redactor	3.0.4
SEOmatic	4.0.33
Site Switcher	2.3.0
Sprig	2.7.2
Typed link field	2.1.5
Workflow	2.0.6

**Comment by engram-design** [comment]
That's odd, and not even sure how that's possible, based off [how Craft](https://github.com/craftcms/cms/blob/ddb107ae0170cd1993b5e97b7af37bf7f6cddd32/src/templates/_layouts/elementindex.twig#L68) renders that JS. `{{ elementInstance.pluralDisplayName()|e("js") }}` is resolved correctly for me.

<img width="718" alt="Screenshot 2023-12-09 at 12 08 52 am" src="https://github.com/verbb/formie/assets/1221575/38c0dc6b-608d-4bd8-be17-211072d84fc4">

Cleared all your caches?

**Comment by karthikkstar** [comment]
@engram-design Just submitted few forms and reload the submission page its works.

Cleared all your caches? - Yes, I cleared all caches except those related to assets.

Thank you

**Comment by karthikkstar** [comment]
@engram-design After DB was restored (3.9.5) and upgraded to Craft 4, I got the same error on the browser console: page not loading.
Now I have cleared all caches on CP. Still not loading.

**Comment by karthikkstar** [comment]
@engram-design This also applies to the Workflow plugin. But setting the page is working fine. Issue with listing page.
/admin/workflow?site=uk

**Comment by engram-design** [comment]
I still can't replicate this, sorry. Any chance you can send your database to `support@verbb.io` for us to take a look at? Haven't had any other reports of this, and wondering if its something specific to your site.
