### ISSUE TITLE
Submission filtering only works on the first field

### ISSUE THREAD

**Issue by soerenmeier** [verbb/formie#2396]
### Describe the bug

I'm expecting to be able to search any field via the Craft filter.
But it seems it's only possible to search the first field.

### Steps to reproduce

1. Create a new Form
2. Add three fields
3. Add a submission
4. search for the second or third field.

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

https://github.com/user-attachments/assets/8485a599-40fc-4af7-8f91-fe797dcfca7e

### Craft CMS version

5.7.3

### Plugin version

3.0.26

### Multi-site?

No

### Additional context

This is a fresh installation. Also occurs in an existing form migrated from craft 4.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.26"`.

**Comment by soerenmeier** [comment]
Thanks

**Comment by engram-design** [comment]
Updated in [3.0.27](https://github.com/verbb/formie/releases/tag/3.0.27).

**Comment by mjniland1** [comment]
I'm still experiencing this issue on 3.0.27 & Craft 5.7.6.


https://github.com/user-attachments/assets/c6f69829-47d1-4069-9345-202b58e937db

**Comment by engram-design** [comment]
I can't seem to replicate that. What sort of fields are these? The only thing I think might be different is that normally fields show their handle and label, while your don't, so maybe something is off there.

<img width="613" alt="Image" src="https://github.com/user-attachments/assets/2364c715-f270-4397-b1bd-c0a3484f37bf" />

**Comment by mjniland1** [comment]
The fields are both Single-Line Text with encryption turned on and a random string used for the handle (a client request). I think the missing handle was tied to the permissions of my fake account. 

![Image](https://github.com/user-attachments/assets/9511082a-51e1-46a9-86e9-8cb7a18eefa8)

**Comment by engram-design** [comment]
Ah yes, content encryption will make a difference here, that's actually a bit of a tricky one here. The encrypted value will always be something unique, so it'll be tricky to compare values for filtering. In order to get around this, we'd have to change the encryption handling of form values to something that's deterministic, which is likely a breaking change, with the potential to lessen the security of things.

So, unfortunately, for now anything encrypted can't be filtered by.

**Comment by mjniland1** [comment]
Bummer but that makes sense. Appreciate the quick reply.
