### ISSUE TITLE
Behavior email templating has changed

### ISSUE THREAD

**Issue by arontseggai** [verbb/formie#2511]
### Describe the bug

Description:
After recent changes, a label is always rendered above custom email templates, even when not explicitly included. This causes formatting issues, especially for third-party systems that scrape the email content in a specific format.

Expected Behavior:
The label should only render if explicitly added in the custom template.

Impact:
This disrupts automated email processing and requires manual cleanup.

Before:

![Image](https://github.com/user-attachments/assets/dfef4324-284e-4283-b800-ee7907a847cd)

After:

![Image](https://github.com/user-attachments/assets/fe368c09-4e5e-48e2-b31f-eefe8a144a50)

Request:
Please adjust the logic so labels only render when explicitly included in the template.

Example of code used in email templating:

`
{% if not (options.hideName ?? false) %}
	{{ field.label | t }}:
{% endif %}

{% if value %}
	{{ value|escape }}
{% else %}
	{{ 'No response.' | t('formie') }}
{% endif %}
`

### Steps to reproduce

1. Set up a custom email template in Formie.
2. Send a form submission email.
3. Observe the unwanted label appearing above the custom template content.

### Form settings

Not relevant.

### Craft CMS version

5.8.8

### Plugin version

3.1.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
I've just added back the `renderOptions.hideName` handling. But also not sure what version you're upgrading from - Formie 2 maybe?

We've actually expanded the number of [available templates](https://github.com/verbb/formie/tree/craft-5/src/templates/_special/email-template) for you to override, so you've got more options. In particular, you might like to override the [field](https://github.com/verbb/formie/blob/craft-5/src/templates/_special/email-template/field.html) template.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.1.1"`.

**Comment by arontseggai** [comment]
Thank you for your fast and detailed response. I really appreciate it.

We’re upgrading from Formie v2 and need to display field labels and values inline (e.g., Administratienummer: 7), which worked previously, but v3 now adds a <strong> label above our custom template (see second image).

 Is there a way to disable Formie’s auto-generated label? The renderOptions.hideName setting doesn’t resolve this.

**Comment by engram-design** [comment]
Formie's email notifications have always shown the label alongside the content, I'm not sure if you're using a custom email template? And if so, then you've got complete control over how the content is shown.

If you are using custom email templates, maybe if you can let me know what files you have, and their contents. Or, if you're not using custom templates, I'm not sure how your first screenshot was possible with a default Formie setup.

**Comment by arontseggai** [comment]
We are using custom email templating to render the notification.

Nothing has changed on our end in the custom templating except that we use field.label instead of field.name since this has been deprecated.

Since the upgrade to v3 the email looks like the after screenshot and in v2 it looked like the before one.

I have added the formie folder as a zip file to show how we render the custom email.

And I will put an example of the number field here inline.

If I comment out the code in our custom email template number.html the label is still showing.

So even with custom templates we don't seem to have control over the strong label on above a field.

Thanks again for your help. Please let me know if anything is still unclear and I will do my best to explain our situation.

[formie.zip](https://github.com/user-attachments/files/21458538/formie.zip)

number.html has code commented out:
<img width="1114" height="637" alt="Image" src="https://github.com/user-attachments/assets/aa9a55b7-2248-4737-b3fc-97a7b5aea5e0" />

Before:
<img width="2084" height="316" alt="Image" src="https://github.com/user-attachments/assets/1382926a-5201-49f8-b241-3fda24dcba43" />

After:
<img width="2066" height="492" alt="Image" src="https://github.com/user-attachments/assets/95b3571c-b458-4008-ba6d-119e32f397b6" />

number.html:
`
{% if not (options.hideName ?? false) %}
	{{ field.label | t }}:
{% endif %}

{% if value %}
	{{ value|escape }}
{% else %}
	{{ 'No response.' | t('formie') }}
{% endif %}
<br>
`

**Comment by engram-design** [comment]
That's the restructuring I was referring to in Formie 3. For each field in a form, it's going to loop through those fields, and render the [field](https://github.com/verbb/formie/blob/craft-5/src/templates/_special/email-template/field.html) template. And while you can indeed override the field-specific template, you still need to override the top-level `field` template as that's now what controls the label.

So in your instance, I believe your templates will not look simplier, if all you want to do is remove the label for all your fields. You now no longer need to override every field's template - unless of course you want to modify how for example the Number field renders its content (not including the label).

**Comment by arontseggai** [comment]
Using the field template it's now working exactly as it should.

We can actually remove all the custom templates and just use the field template.

Thanks you for your explanation and quick answers.

I will close this issue now.
