### ISSUE TITLE
Issues when using file upload field inside a repeater

### ISSUE THREAD

**Issue by d-karstens** [verbb/formie#2600]
### Describe the bug

Hi, 

We've encountered two issues when using a file upload field inside a repeater field, the first being that files are not being attached to email notifications with no error message shown

The second is that we want submissions and files to be deleted after an hour, but when the data retention cleanup is run files and submissions are not deleted. There's no error displayed immediately, but when trying to prune the submissions using the console I can see the following error `Failed to prune submission with ID: #3255. Call to a member function all() on null`

Unsure if these are related to the same problem, but have just opened the one issue as they both only happen when using file uploads inside repeaters

Let me know if you need any more information,
Thanks!

### Steps to reproduce

1. Create a form with a File Upload field inside a Repeater field
2. Add an email notification with `Attach File Uploads` enabled
3. Set the data retention settings to delete files after 1 minute
4. Create a submission to receive an email with no attached files
5. Use `formie/gc/prune-data-retention-submissions` command to replicate submission pruning error

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.8.18 

### Plugin version

3.1.4

### Multi-site?

No

**Comment by engram-design** [comment]
Both issues should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.1.4"`.

**Comment by d-karstens** [comment]
Thank you! Pruning submissions appears to be working correctly now, however there seems to still be an issue with email attachments that I'm having a hard time replicating

We have quite a long form with 10 pages and 5 file upload fields, two of which are inside repeaters and two only shown conditionally. When testing with this update only files from a repeater on the last page are being attached

I've tried replicating this with a new form that has two pages and a repeater with a file upload field in each but was not getting the issue, and when using the "Send Test Email" button in the notification preview it wasn't happening either so I'm unsure what is causing it

Sorry it's not much to go off, but I can email an export of the form if that would be helpful

**Comment by engram-design** [comment]
Interesting. Yep, shoot through a support email (Formie > Settings > Get Support) and I'll see if I can replicate that.

**Comment by engram-design** [comment]
Thanks for sending that through. Just wanted to confirm, can you check your submission actually contains values for that content as well?

**Comment by d-karstens** [comment]
It looks like the files are not attached in the submission, though they are uploaded and I can see them under Assets in the CMS

**Comment by d-karstens** [comment]
Unsure if it's related, or a different issue but in this instance where a file was uploaded to the first repeater the file upload appears to be blank, and the second has the file like in the other cases

<img width="519" height="212" alt="Image" src="https://github.com/user-attachments/assets/d0d5601f-f013-45aa-b013-40c86883581b" />
<img width="906" height="216" alt="Image" src="https://github.com/user-attachments/assets/a2054ee6-8448-46cf-92b8-a58f4cc2a0d3" />

**Comment by engram-design** [comment]
Thanks for confirming. Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.1.4"`.

**Comment by d-karstens** [comment]
Thanks for the quick fix! That appears to have mostly fixed the issues - a last thing I've noticed is when uploading a file upload field in the form that is _not_ inside a Group or Repeater it doesn't seem to be uploaded

I've recorded a short video demonstrating uploading a file, going to the next page, then going back and seeing the file is missing from the field. 

https://github.com/user-attachments/assets/327e91db-e3bd-4c63-b3e8-9c2fe778fef3

Seems like the other file uploads are working correctly though!

**Comment by engram-design** [comment]
Are these actually uploaded to the submission though? Check out the Incomplete submission in the control panel to see if the assets are actually there.

It's normal behaviour at the moment for Ajax forms; there's no visual feedback when you upload and navigate back to the field. That's because we can't populate a `input type="file"` field due to browser restrictions. If you refresh the page, you'll likely see a note of the uploaded file, but that's not built for Ajax forms yet.

And, to save handling, whenever you submit a page with a File Upload field, Formie will reset the input, so that it's not uploaded _again_ for every future page submission.

**Comment by d-karstens** [comment]
Ah okay, makes sense. Oddly enough I can see the file is attached to the incomplete submission when I upload it on page 8 of the form and go to page 9, but it seems to be missing from the submission when going from page 9 to 10 before submitting the form, and still missing when submitting

**Comment by engram-design** [comment]
Good call. I've actually made some further steps towards a larger improvement of this, where File Upload fields now have their uploaded Asset IDs returned for Ajax forms. I believe that should address things here.

To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.1.4"`.

**Comment by d-karstens** [comment]
Have just done a couple tests and that appears to have fixed the issues, thank you!

**Comment by d-karstens** [comment]
Sorry, seems there's one last issue that has just popped up!

We had an email field inside a group field that was mapped to an email notification, and after updating to `dev-craft-5 as 3.1.4` we've noticed a bunch of errors in our queue manager saying `Failed to send notification email: {"error":"Notification email error. No recipient email address found."}. `, but in the job data I can see the email addresses are there.

I can also replicate this by creating a new form with only an email field inside a group, setting up a new email notification and trying to preview it

<img width="631" height="227" alt="Image" src="https://github.com/user-attachments/assets/ded8fa03-e6b9-4d0f-941a-cf3e5680300e" />

<img width="802" height="782" alt="Image" src="https://github.com/user-attachments/assets/fd77bdce-238c-465b-832b-eafa55ee4cb6" />

<img width="804" height="524" alt="Image" src="https://github.com/user-attachments/assets/bfd91d3f-3714-4331-8ae0-9cb0d9dd59f3" />

Confirming that this does not happen when downgrading again to the 3.1.4 release

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.1.4"`.

**Comment by engram-design** [comment]
Updated in [3.1.5](https://github.com/verbb/formie/releases/tag/3.1.5).
