### ISSUE TITLE
deleteSubmission Mutation does not work

### ISSUE THREAD

**Issue by angrotheman** [verbb/formie#270]
**Description**

If I want to remove a submission with a GraphQL mutation, nothing happens.
Even with the Full Schema in GraphiQL - This means that it is not a permission Issue.

GraphQL returns the right output
`{
    "data": {
        "deleteSubmission": true
    }
}`

But the form is still there.

**Steps to reproduce**
1. Create a form
2. Try to remove it with a GraphQL Mutation

**Comment by engram-design** [comment]
Just to confirm, you're trying to delete a form submission, not a form itself? I note in your reproduction steps mentioning the "form is still there" and trying to remove the form you've created.

However, looks like there was an error when deleting a submission, which should be fixed in [1.3.5](https://github.com/verbb/formie/releases/tag/1.3.5)

Let me know if you still have issues.

**Comment by angrotheman** [comment]
> Just to confirm, you're trying to delete a form submission, not a form itself? I note in your reproduction steps mentioning the "form is still there" and trying to remove the form you've created.
> 
> 
> 
> However, looks like there was an error when deleting a submission, which should be fixed in [1.3.5](https://github.com/verbb/formie/releases/tag/1.3.5)
> 
> 
> 
> Let me know if you still have issues.

You're absolutely right. I explained my reproduction steps just badly. No, I tried to remove a submission - not a form! I will do the update later.

**Comment by angrotheman** [comment]
I updated now but the issue is still there without any changes and with the same response. 

`mutation MyQuery {
  deleteSubmission(id: 164394)
}`

**Comment by engram-design** [comment]
Hmm, I'll see what I can do about this, as it seems to be working on my end. Are there any errors if you manually delete the submission in the control panel, or restore it?

**Comment by angrotheman** [comment]
Could it have something to do with a multi language site? Manual deletion works fine.

**Comment by engram-design** [comment]
It _shouldn't_ (also testing on a multi-site), but will keep testing.

**Comment by engram-design** [comment]
@angrotheman Ah - maybe this is when you're trying to delete a submission on the non-default site? If so, I can confirm this behaves this way.

**Comment by angrotheman** [comment]
@engram-design Yes, that's it! I hadn't tried it on the default site before. When I just tried to remove a submission from the default site, it works fine! So, the deleteSubmission Mutation does not work on non-default sites!

**Comment by engram-design** [comment]
Should be fixed in [1.3.7](https://github.com/verbb/formie/releases/tag/1.3.7)

**Comment by angrotheman** [comment]
Great! Now it works :) Maybe you should include the siteId property to the GraphiQL Explorer? I'm currently getting an error there because of an unknown argument.

**Comment by engram-design** [comment]
You might just need to clear your GraphQL caches? 
<img width="304" alt="Screen Shot 2020-12-24 at 1 52 44 pm" src="https://user-images.githubusercontent.com/1221575/103055792-5164e880-45ef-11eb-832b-2d5df04b7156.png">

**Comment by angrotheman** [comment]
Yes. Now this also works! Have a good holiday season :)
