### ISSUE TITLE
Elements Field not pre-populating when it's given a limit

### ISSUE THREAD

**Issue by bryantAXS** [verbb/formie#401]
**Description**
I was noticing that one of our Elements fields wasn't capturing any data. When I looked at the field itself, it was only showing 1 element inside the select dropdown. I removed the `Limit` setting inside the field and things started to populate correctly again.

My assumption was that the `Limit` on that field was intended to be for the number a user could select, but maybe not?

https://share.getcloudapp.com/geu49EkG

**Steps to reproduce**
1. Create an Entries field on a form
2. Give it a limit
3. Render form

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 3.19.1
- Craft version: 3.5.19
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Yep, so this is a bit of an issue in that limit get applied first, then the default value you're trying to populate afterwards. So it'll limit the number of entries shown (to say 1), then try and set the default value to an entry (say the 10th in order), but can't.

Should be fixed in [1.3.23](https://github.com/verbb/formie/releases/tag/1.3.23)

**Comment by Mosnar** [comment]
@engram-design Just ran into this issue where our client noticed there was only one item in the dropdown. Removing the limit of one fixed it. We are running 1.3.23. I tried resaving the form with the limit of "1" and that also did not fix it. Is there another step I should be taking?

**Comment by engram-design** [comment]
@Mosnar Sorry about that, should be fixed in [1.3.24](https://github.com/verbb/formie/releases/tag/1.3.24)
